image: node

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

stages:
  - prep
  - build
  - test

before_script:
  - npm ci --cache .npm --prefer-offline

build the app:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - ./dist

unit tests:
  stage: test
  script:
    - npm run test


cypress tests:
  stage: test
  script:
    - npm install cypress
    - npm install -g wait-on
    - npm run start -- --port 3333  & wait-on http://localhost:3333
    - ./node_modules/.bin/cypress run 
