image: node:15.4.0-buster

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

stages:
  - build
  - test
  - deploy master

build  config:
  stage: build
  image: alpine
  only:
    - master
    - merge_requests
  script:
    - sed -i "s/%%TESTING_DOMAIN%%/$TESTING_IP/" ./cypress.json
    - sed -i "s/%%TESTING_PORT%%/$APP_PORT/" ./cypress.json
  artifacts:
    paths:
      - ./cypress.json

build app:
  stage: build
  only:
    - master
    - merge_requests
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - sed -i "s/%%APP_NAME%%/$APP_NICE_NAME/" ./nuxt.config.js
    - npm run generate
  artifacts:
    paths:
      - ./dist

artifact test:
  image: alpine
  only:
    - master
    - merge_requests
  stage: test
  script:
    - grep -q $TESTING_IP ./cypress.json
    - grep -q $APP_PORT ./cypress.json

unit tests:
  only:
    - master
    - merge_requests
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test

cypress tests:
  only:
    - master
    - merge_requests
  image: docker:18.06
  services:
    - docker:18.06-dind
  stage: test
  before_script:
    - cp ./cypress/ci/integration-test.md ./content/articles/integration-test.md
    - docker build -t cypresstest .
    - docker pull cypress/included:3.2.0
    - docker network create $TESTING_NETWORK
  script:
    - docker run -d -p $APP_PORT:$APP_PORT --network $TESTING_NETWORK --name=app cypresstest
    - sleep 5
    - docker run -v $(pwd):/e2e -w /e2e --network $TESTING_NETWORK cypress/included:3.2.0
  artifacts:
    when: on_failure
    expire_in: 1 day
    paths:
      - './cypress/screenshots'
      - './cypress/videos'

deploy master:
  only:
    - master
  cache: {}
  variables:
    DOMAIN: jamstore-master.surge.sh
  stage: deploy master
  before_script:
    - npm install --global surge
  script:
    - surge --project ./dist --domain $DOMAIN
