image: node

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

stages:
  - prep
  - build
  - test

before_script:
  - npm ci --cache .npm --prefer-offline

build the app:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - ./dist

unit tests:
  stage: test
  script:
    - npm run test


cypress tests:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - ''
  stage: test
  script:
    - sed -i 's/%CYPRESS_DOMAIN%/$CYPRESS_DOMAIN/' ./cypress.json
    - sed -i 's/%CYPRESS_PORT%/$CYPRESS_PORT/' ./cypress.json
    - docker build -t cypresstest .
    - docker run -d cypresstest
    - docker run -it -v $(pwd):/e2e -w /e2e cypress/included:3.2.0

