image: node

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

stages:
  - build
  - test

before_script:
  - npm ci --cache .npm --prefer-offline


build the app:
  stage: build
  script:
    - npm run build

unit tests:
  stage: test
  script:
    - npm run test
