image: node

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

stages:
  - prep
  - build
  - test

before_script:
  - npm ci --cache .npm --prefer-offline

build app:
  stage: build
  script:
    - sed -i "s/%%TESTING_DOMAIN%%/$TESTING_IP/" ./cypress.json
    - sed -i "s/%%TESTING_PORT%%/$APP_PORT/" ./cypress.json
    - npm run generate
  artifacts:
    paths:
      - ./dist
      - ./cypress.json

artifact test:
  image: alpine
  stage: test
  before_script:
    - ''
  script:
    - grep -q $TESTING_IP ./cypress.json
    - grep -q $APP_PORT ./cypress.json

unit tests:
  stage: test
  script:
    - npm run test

cypress tests:
  image: docker:20.10.0
  services:
    - docker:20.10.0-dind
  stage: test
  before_script:
    - docker build -t cypresstest .
    - docker pull cypress/included:3.2.0
    - docker network create --subnet=$TESTING_SUBNET $TESTING_NETWORK
  script:
    - docker run -d -p $APP_PORT:$APP_PORT --network $TESTING_NETWORK --ip=$TESTING_IP cypresstest
    - sleep 5
    - docker run -v $(pwd):/e2e -w /e2e --network $TESTING_NETWORK cypress/included:3.2.0
